services:
  backend:
    build:
      context: ./back
    volumes:
      - ./back:/app
    ports:
      - "8080:8080"
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=prod
    depends_on:
      - db

  frontend:
    build:
      context: ./front
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messenger
    ports:
      - "5433:5432"
