version: '3.8'

services:
  backend:
    build:
      context: ./back
    volumes:
      - ./back:/app
    ports:
      - "8080:8080"
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=prod
    depends_on:
      - db
      - rabbitmq

  frontend:
    build:
      context: ./front
      target: development
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messenger
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

