name: Update Submodules on External Push

on:
  repository_dispatch:
    types: [update-submodules]

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules to latest commit
        run: |
          rm -rf .git/modules/front
          rm -rf .git/modules/back
          rm -rf front
          rm -rf back
          git config user.name "dasha-sync"
          git config user.email ${{ secrets.EMAIL }}
          git submodule update --init --remote

      - name: Commit and push changes if any
        run: |
          git config user.name "dasha-sync"
          git config user.email ${{ secrets.EMAIL }}
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: auto-update submodules from dispatch"
            git push
          fi
